import type { WeeklyMealPlan, PlannedMeal, SnackItem, UserPreferences, Recipe, CuisinePreference } from "@/types";

// Full recipe library — server-only (not bundled client-side)
let _recipeLibrary: Recipe[] | null = null;
function getRecipeLibrary(): Recipe[] {
  if (!_recipeLibrary) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      _recipeLibrary = require("../data/recipes.json") as Recipe[];
    } catch {
      _recipeLibrary = null;
    }
  }
  return _recipeLibrary ?? MOCK_RECIPES;
}

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    description: "A rich, creamy tomato-based curry with tender marinated chicken. A crowd-pleasing classic that feels special on a weeknight.",
    cuisine: "indian",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 35,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "chicken breast fillets", quantity: 800, unit: "g" },
      { name: "Greek yogurt", quantity: 200, unit: "g" },
      { name: "garam masala", quantity: 2, unit: "tsp" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "turmeric", quantity: 1, unit: "tsp" },
      { name: "smoked paprika", quantity: 1, unit: "tsp" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "fresh ginger", quantity: 30, unit: "g" },
      { name: "crushed tomatoes", quantity: 400, unit: "g" },
      { name: "thickened cream", quantity: 150, unit: "ml" },
      { name: "vegetable oil", quantity: 2, unit: "tbsp" },
      { name: "basmati rice", quantity: 300, unit: "g" },
      { name: "fresh coriander", quantity: 1, unit: "bunch" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
    ],
    method: [
      "Cut chicken into chunks. Mix yogurt with half the spices, coat chicken and marinate 15 minutes.",
      "Cook rice according to packet instructions.",
      "Heat oil in a large pan over medium-high heat. Cook chicken in batches until charred, 3–4 minutes per side. Set aside.",
      "In the same pan, fry onion until golden, 5 minutes. Add garlic and ginger, cook 1 minute.",
      "Add remaining spices, stir 30 seconds. Pour in crushed tomatoes, simmer 10 minutes.",
      "Stir in cream and return chicken to pan. Simmer 5 minutes until cooked through.",
      "Season, garnish with coriander and serve with rice.",
    ],
    tags: ["family-friendly", "freezer-friendly", "dairy"],
    imageQuery: "chicken tikka masala curry bowl",
    estimatedCost: 22,
  },
  {
    id: "spaghetti-bolognese",
    name: "Spaghetti Bolognese",
    description: "A slow-simmered beef ragù with rich tomato depth. The kind of pasta that improves as it rests.",
    cuisine: "italian",
    primaryProtein: "beef",
    servings: 4,
    cookTimeMinutes: 45,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "beef mince", quantity: 500, unit: "g" },
      { name: "spaghetti", quantity: 400, unit: "g" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "carrot", quantity: 1, unit: "each" },
      { name: "celery", quantity: 2, unit: "each", notes: "stalks" },
      { name: "crushed tomatoes", quantity: 400, unit: "g" },
      { name: "tomato paste", quantity: 2, unit: "tbsp" },
      { name: "beef stock", quantity: 250, unit: "ml" },
      { name: "dried oregano", quantity: 1, unit: "tsp" },
      { name: "olive oil extra virgin", quantity: 2, unit: "tbsp" },
      { name: "parmesan grated", quantity: 60, unit: "g" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
      { name: "black pepper", quantity: 0.5, unit: "tsp" },
    ],
    method: [
      "Finely dice onion, carrot and celery. Mince garlic.",
      "Heat oil in a heavy-based pot. Cook onion, carrot and celery 8 minutes until softened.",
      "Add garlic and cook 1 minute. Add mince, breaking up with a spoon, cook until browned.",
      "Stir in tomato paste and cook 2 minutes. Add crushed tomatoes, stock and oregano.",
      "Simmer uncovered on low heat 30 minutes, stirring occasionally, until thickened.",
      "Cook spaghetti in salted boiling water until al dente. Reserve ½ cup pasta water.",
      "Toss pasta with ragù, adding pasta water to loosen. Serve with parmesan.",
    ],
    tags: ["family-friendly", "freezer-friendly", "classic"],
    imageQuery: "spaghetti bolognese pasta bowl",
    estimatedCost: 18,
  },
  {
    id: "thai-green-curry",
    name: "Thai Green Curry",
    description: "Fragrant coconut milk curry with tender chicken and vibrant vegetables. On the table in under 30 minutes.",
    cuisine: "thai",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 25,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "chicken thigh fillets", quantity: 700, unit: "g" },
      { name: "coconut milk", quantity: 400, unit: "ml" },
      { name: "coconut cream", quantity: 200, unit: "ml" },
      { name: "green capsicum", quantity: 1, unit: "each" },
      { name: "zucchini", quantity: 2, unit: "each" },
      { name: "baby spinach", quantity: 120, unit: "g" },
      { name: "fish sauce", quantity: 2, unit: "tbsp" },
      { name: "basmati rice", quantity: 300, unit: "g" },
      { name: "lime", quantity: 2, unit: "each" },
      { name: "fresh coriander", quantity: 1, unit: "bunch" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
      { name: "vegetable oil", quantity: 1, unit: "tbsp" },
    ],
    method: [
      "Cook rice per packet instructions.",
      "Slice chicken into strips. Chop capsicum and zucchini into bite-sized pieces.",
      "Heat oil in a wok over high heat. Stir-fry chicken until golden, 4 minutes. Set aside.",
      "Pour coconut milk and cream into wok. Bring to a simmer, add capsicum and zucchini.",
      "Cook vegetables 5 minutes. Return chicken, add fish sauce. Simmer 3 minutes.",
      "Stir in spinach until wilted. Squeeze in lime juice.",
      "Serve over rice, garnished with coriander and sliced spring onions.",
    ],
    tags: ["quick", "gluten-free", "dairy-free"],
    imageQuery: "thai green curry coconut bowl",
    estimatedCost: 20,
  },
  {
    id: "greek-lamb-salad",
    name: "Greek Lamb Salad",
    description: "Marinated lamb backstrap over a vibrant Greek salad with feta and kalamata olives. Mediterranean at its best.",
    cuisine: "greek",
    primaryProtein: "lamb",
    servings: 4,
    cookTimeMinutes: 15,
    prepTimeMinutes: 20,
    difficulty: "easy",
    ingredients: [
      { name: "lamb cutlets", quantity: 600, unit: "g" },
      { name: "olive oil extra virgin", quantity: 4, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "clove" },
      { name: "dried oregano", quantity: 2, unit: "tsp" },
      { name: "lemon", quantity: 2, unit: "each" },
      { name: "cherry tomatoes", quantity: 250, unit: "g" },
      { name: "lebanese cucumber", quantity: 2, unit: "each" },
      { name: "red onion", quantity: 0.5, unit: "each" },
      { name: "kalamata olives", quantity: 150, unit: "g" },
      { name: "feta cheese", quantity: 200, unit: "g" },
      { name: "baby spinach", quantity: 120, unit: "g" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
    ],
    method: [
      "Combine 2 tbsp olive oil, crushed garlic, oregano and lemon zest. Coat lamb and rest 10 minutes.",
      "Halve tomatoes, slice cucumber, thinly slice red onion.",
      "Toss salad ingredients with remaining olive oil and lemon juice. Season.",
      "Heat a grill pan over high heat. Cook lamb cutlets 3 minutes per side for medium. Rest 3 minutes.",
      "Slice lamb and arrange over salad. Crumble feta over top.",
    ],
    tags: ["gluten-free", "quick", "low-carb"],
    imageQuery: "greek lamb salad feta olives",
    estimatedCost: 28,
  },
  {
    id: "pork-stir-fry-noodles",
    name: "Pork & Vegetable Stir-Fry Noodles",
    description: "Silky rice noodles tossed with pork strips and crisp vegetables in a savoury soy-sesame sauce.",
    cuisine: "asian",
    primaryProtein: "pork",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 15,
    difficulty: "easy",
    ingredients: [
      { name: "pork stir fry strips", quantity: 500, unit: "g" },
      { name: "vermicelli rice noodles", quantity: 400, unit: "g" },
      { name: "bok choy", quantity: 3, unit: "each" },
      { name: "carrot", quantity: 2, unit: "each" },
      { name: "snow peas", quantity: 150, unit: "g" },
      { name: "soy sauce", quantity: 3, unit: "tbsp" },
      { name: "oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "sesame oil", quantity: 1, unit: "tbsp" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "fresh ginger", quantity: 20, unit: "g" },
      { name: "vegetable oil", quantity: 2, unit: "tbsp" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
    ],
    method: [
      "Soak noodles in boiling water 4 minutes, drain and rinse with cold water.",
      "Mix soy sauce, oyster sauce and sesame oil in a bowl. Set aside.",
      "Heat wok over very high heat. Add oil, stir-fry pork 3 minutes until caramelised. Remove.",
      "Add garlic and ginger, cook 30 seconds. Add carrot and snow peas, stir-fry 2 minutes.",
      "Add bok choy, toss 1 minute until wilted. Return pork and add noodles.",
      "Pour sauce over and toss everything together over high heat, 1 minute.",
      "Serve topped with sliced spring onions.",
    ],
    tags: ["quick", "dairy-free"],
    imageQuery: "asian pork noodle stir fry wok",
    estimatedCost: 18,
  },
  {
    id: "salmon-traybake",
    name: "Lemon Herb Salmon Traybake",
    description: "One-pan salmon with roasted sweet potato and asparagus. Effortless, healthy, and packed with flavour.",
    cuisine: "australian",
    primaryProtein: "seafood",
    servings: 4,
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "tasmanian atlantic salmon portions", quantity: 600, unit: "g" },
      { name: "sweet potato", quantity: 600, unit: "g" },
      { name: "asparagus", quantity: 2, unit: "bunch" },
      { name: "cherry tomatoes", quantity: 250, unit: "g" },
      { name: "olive oil extra virgin", quantity: 3, unit: "tbsp" },
      { name: "lemon", quantity: 2, unit: "each" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "fresh thyme", quantity: 1, unit: "pack" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
      { name: "black pepper", quantity: 0.5, unit: "tsp" },
    ],
    method: [
      "Preheat oven to 200°C. Peel and cube sweet potato into 2cm pieces.",
      "Toss sweet potato with 2 tbsp olive oil, salt and pepper. Roast 15 minutes.",
      "Add asparagus and cherry tomatoes to tray. Nestle salmon portions on top.",
      "Drizzle salmon with remaining olive oil, top with sliced garlic and thyme sprigs.",
      "Squeeze half the lemon over everything. Roast 15 minutes until salmon is just cooked.",
      "Serve with remaining lemon wedges.",
    ],
    tags: ["gluten-free", "dairy-free", "one-pan", "healthy"],
    imageQuery: "salmon traybake sweet potato asparagus",
    estimatedCost: 32,
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Silky, mild tomato-cream sauce with tender chicken pieces. A family favourite that tastes like it cooked all day.",
    cuisine: "indian",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "chicken thigh fillets", quantity: 800, unit: "g" },
      { name: "butter", quantity: 60, unit: "g" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "fresh ginger", quantity: 20, unit: "g" },
      { name: "garam masala", quantity: 2, unit: "tsp" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "crushed tomatoes", quantity: 400, unit: "g" },
      { name: "thickened cream", quantity: 200, unit: "ml" },
      { name: "basmati rice", quantity: 300, unit: "g" },
      { name: "fresh coriander", quantity: 1, unit: "bunch" },
    ],
    method: [
      "Cook rice per packet instructions.",
      "Melt butter in a large pan over medium heat. Cook onion until soft, 5 minutes. Add garlic and ginger, cook 1 minute.",
      "Add garam masala and cumin, stir 30 seconds. Pour in crushed tomatoes, simmer 8 minutes.",
      "Blend sauce until smooth. Return to pan, stir in cream and bring to a gentle simmer.",
      "Add chicken and cook 15 minutes until cooked through. Season to taste.",
      "Serve over rice, garnished with coriander.",
    ],
    tags: ["family-friendly", "freezer-friendly"],
    imageQuery: "butter chicken curry rice",
    estimatedCost: 20,
  },
  {
    id: "mushroom-pasta",
    name: "Creamy Mushroom Pasta",
    description: "Earthy mushrooms in a rich garlic-parmesan cream sauce. A satisfying meat-free weeknight dinner.",
    cuisine: "italian",
    primaryProtein: "tofu",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "penne pasta", quantity: 400, unit: "g" },
      { name: "mixed mushrooms", quantity: 500, unit: "g" },
      { name: "thickened cream", quantity: 300, unit: "ml" },
      { name: "parmesan grated", quantity: 80, unit: "g" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "butter", quantity: 40, unit: "g" },
      { name: "fresh thyme", quantity: 1, unit: "pack" },
      { name: "white wine", quantity: 100, unit: "ml" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
      { name: "black pepper", quantity: 0.5, unit: "tsp" },
    ],
    method: [
      "Cook pasta in salted boiling water until al dente. Reserve 1 cup pasta water.",
      "Melt butter in a large frying pan over high heat. Cook mushrooms without stirring until golden, 4 minutes.",
      "Add garlic and thyme, cook 1 minute. Deglaze with white wine, cook until mostly evaporated.",
      "Pour in cream and simmer 3 minutes until slightly thickened.",
      "Toss in drained pasta and half the parmesan. Add pasta water to loosen as needed.",
      "Serve topped with remaining parmesan and cracked pepper.",
    ],
    tags: ["vegetarian", "quick"],
    imageQuery: "creamy mushroom pasta parmesan",
    estimatedCost: 15,
  },
  {
    id: "pad-thai",
    name: "Prawn Pad Thai",
    description: "Classic Thai street noodles with king prawns, egg, and crispy bean sprouts in a tangy tamarind sauce.",
    cuisine: "thai",
    primaryProtein: "seafood",
    servings: 4,
    cookTimeMinutes: 15,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "raw king prawns", quantity: 500, unit: "g" },
      { name: "rice stick noodles", quantity: 300, unit: "g" },
      { name: "eggs", quantity: 3, unit: "each" },
      { name: "bean sprouts", quantity: 200, unit: "g" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
      { name: "fish sauce", quantity: 3, unit: "tbsp" },
      { name: "oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "lime", quantity: 2, unit: "each" },
      { name: "roasted peanuts", quantity: 80, unit: "g" },
      { name: "vegetable oil", quantity: 2, unit: "tbsp" },
    ],
    method: [
      "Soak noodles in warm water 20 minutes, drain.",
      "Mix fish sauce, oyster sauce and lime juice together.",
      "Heat wok over very high heat. Stir-fry prawns 2 minutes until pink. Push to side.",
      "Add noodles and sauce, toss 2 minutes. Push aside, scramble eggs in centre.",
      "Fold everything together. Add bean sprouts and half the spring onions, toss 1 minute.",
      "Serve topped with peanuts and remaining spring onions with lime wedges.",
    ],
    tags: ["quick", "dairy-free", "gluten-free"],
    imageQuery: "pad thai prawns noodles lime",
    estimatedCost: 24,
  },
  {
    id: "chicken-quesadillas",
    name: "Chicken & Cheese Quesadillas",
    description: "Crispy golden tortillas stuffed with spiced chicken, melted cheese and capsicum. Ready in 20 minutes.",
    cuisine: "mexican",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "chicken breast fillets", quantity: 600, unit: "g" },
      { name: "large flour tortillas", quantity: 1, unit: "pack" },
      { name: "tasty cheese block", quantity: 200, unit: "g" },
      { name: "red capsicum", quantity: 2, unit: "each" },
      { name: "red onion", quantity: 1, unit: "each" },
      { name: "smoked paprika", quantity: 2, unit: "tsp" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "sour cream", quantity: 150, unit: "ml" },
      { name: "hass avocados", quantity: 2, unit: "each" },
      { name: "lime", quantity: 1, unit: "each" },
      { name: "vegetable oil", quantity: 1, unit: "tbsp" },
    ],
    method: [
      "Season chicken with paprika and cumin. Cook in oil in a pan 5 minutes per side until cooked. Slice thinly.",
      "Sauté sliced capsicum and onion until soft, 5 minutes.",
      "Lay a tortilla flat. Top half with grated cheese, chicken and capsicum mix. Fold in half.",
      "Cook quesadilla in a dry pan over medium heat, 2 minutes per side until golden and crispy.",
      "Mash avocado with lime juice and salt.",
      "Slice into wedges. Serve with avocado and sour cream.",
    ],
    tags: ["quick", "family-friendly"],
    imageQuery: "chicken quesadillas avocado sour cream",
    estimatedCost: 20,
  },
  {
    id: "beef-fried-rice",
    name: "Beef & Egg Fried Rice",
    description: "Smoky wok-fried rice with tender beef strips, egg, and vegetables. Better than takeaway and on the table in 20 minutes.",
    cuisine: "asian",
    primaryProtein: "beef",
    servings: 4,
    cookTimeMinutes: 15,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "beef stir fry strips", quantity: 400, unit: "g" },
      { name: "steamed jasmine rice", quantity: 2, unit: "cups", notes: "cooked and cooled" },
      { name: "eggs", quantity: 3, unit: "each" },
      { name: "frozen peas & corn", quantity: 250, unit: "g" },
      { name: "carrot", quantity: 2, unit: "each" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
      { name: "soy sauce", quantity: 4, unit: "tbsp" },
      { name: "oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "sesame oil", quantity: 1, unit: "tbsp" },
      { name: "vegetable oil", quantity: 2, unit: "tbsp" },
    ],
    method: [
      "Heat wok over maximum heat. Add oil, stir-fry beef 2 minutes until caramelised. Remove.",
      "Add carrots and peas, stir-fry 2 minutes. Push to side.",
      "Crack eggs into centre, scramble until just set, then fold through vegetables.",
      "Add cold rice and sauces. Toss everything over high heat 3 minutes until rice is slightly crispy.",
      "Return beef and toss through.",
      "Serve topped with sliced spring onions and a drizzle of sesame oil.",
    ],
    tags: ["quick", "dairy-free"],
    imageQuery: "beef fried rice wok egg",
    estimatedCost: 18,
  },
  {
    id: "lamb-souvlaki",
    name: "Lamb Souvlaki Wraps",
    description: "Tender marinated lamb skewers in warm pita with tzatziki, tomato and red onion. Tastes like a Greek holiday.",
    cuisine: "greek",
    primaryProtein: "lamb",
    servings: 4,
    cookTimeMinutes: 15,
    prepTimeMinutes: 20,
    difficulty: "easy",
    ingredients: [
      { name: "lamb leg diced", quantity: 700, unit: "g" },
      { name: "pita bread", quantity: 1, unit: "pack" },
      { name: "olive oil extra virgin", quantity: 3, unit: "tbsp" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "dried oregano", quantity: 2, unit: "tsp" },
      { name: "lemon", quantity: 2, unit: "each" },
      { name: "greek yogurt", quantity: 200, unit: "g" },
      { name: "lebanese cucumber", quantity: 1, unit: "each" },
      { name: "cherry tomatoes", quantity: 200, unit: "g" },
      { name: "red onion", quantity: 0.5, unit: "each" },
    ],
    method: [
      "Combine olive oil, garlic, oregano and lemon zest. Toss with lamb and marinate 15 minutes.",
      "Make tzatziki: grate and squeeze cucumber dry. Mix with yogurt, crushed garlic and lemon juice. Season.",
      "Thread lamb onto skewers. Grill or pan-fry over high heat 3 minutes per side until charred.",
      "Warm pita in a dry pan 30 seconds per side.",
      "Assemble wraps with lamb, tzatziki, halved cherry tomatoes and sliced red onion.",
    ],
    tags: ["quick", "family-friendly"],
    imageQuery: "lamb souvlaki pita tzatziki",
    estimatedCost: 26,
  },
  {
    id: "honey-garlic-chicken",
    name: "Honey Garlic Chicken Tray Bake",
    description: "Golden chicken thighs roasted with potatoes and greens in a sticky honey-garlic glaze. One tray, zero fuss.",
    cuisine: "australian",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 35,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "chicken thigh cutlets", quantity: 8, unit: "each" },
      { name: "baby potatoes", quantity: 600, unit: "g" },
      { name: "broccolini", quantity: 2, unit: "bunch" },
      { name: "honey", quantity: 3, unit: "tbsp" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "olive oil extra virgin", quantity: 2, unit: "tbsp" },
      { name: "lemon", quantity: 1, unit: "each" },
      { name: "sea salt", quantity: 1, unit: "tsp" },
    ],
    method: [
      "Preheat oven to 200°C. Mix honey, soy sauce and crushed garlic.",
      "Halve potatoes. Toss with olive oil, salt and half the glaze. Roast 20 minutes.",
      "Push potatoes to the side. Add chicken skin-side up, brush generously with remaining glaze.",
      "Roast 15 minutes. Add broccolini to tray, roast a final 5 minutes.",
      "Rest 3 minutes. Serve with lemon wedges.",
    ],
    tags: ["one-pan", "gluten-free", "family-friendly"],
    imageQuery: "honey garlic chicken tray bake potatoes",
    estimatedCost: 22,
  },
  {
    id: "beef-tacos",
    name: "Smoky Beef Tacos",
    description: "Spiced beef mince in warm tortillas with all the trimmings. A crowd favourite that comes together in 20 minutes.",
    cuisine: "mexican",
    primaryProtein: "beef",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "beef mince", quantity: 600, unit: "g" },
      { name: "tortillas", quantity: 1, unit: "pack" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "smoked paprika", quantity: 2, unit: "tsp" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "chilli flakes", quantity: 0.5, unit: "tsp" },
      { name: "crushed tomatoes", quantity: 200, unit: "g" },
      { name: "hass avocados", quantity: 2, unit: "each" },
      { name: "lime", quantity: 2, unit: "each" },
      { name: "cherry tomatoes", quantity: 250, unit: "g" },
      { name: "sour cream", quantity: 200, unit: "ml" },
      { name: "tasty cheese block", quantity: 100, unit: "g" },
      { name: "vegetable oil", quantity: 1, unit: "tbsp" },
    ],
    method: [
      "Dice onion, halve cherry tomatoes. Mash avocado with lime juice and salt.",
      "Heat oil in a pan. Cook onion until soft, 4 minutes. Add garlic and spices, cook 1 minute.",
      "Add mince, breaking up, cook until browned 5 minutes. Pour in tomatoes, simmer 5 minutes.",
      "Warm tortillas in a dry pan or microwave.",
      "Set up a taco bar: beef, avocado, cherry tomatoes, sour cream, grated cheese.",
      "Build tacos at the table — squeeze fresh lime over the top.",
    ],
    tags: ["quick", "family-friendly", "crowd-pleaser"],
    imageQuery: "beef tacos avocado lime mexican",
    estimatedCost: 22,
  },

  // ── Middle Eastern ────────────────────────────────────────────────────────
  {
    id: "lamb-kofta-hummus",
    name: "Lamb Kofta & Hummus",
    description: "Spiced lamb meatballs on creamy hummus with warm pita — a Middle Eastern mezze platter at home.",
    cuisine: "middle-eastern",
    primaryProtein: "lamb",
    servings: 4,
    cookTimeMinutes: 25,
    prepTimeMinutes: 20,
    difficulty: "easy",
    ingredients: [
      { name: "lamb mince", quantity: 600, unit: "g" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "ground cumin", quantity: 2, unit: "tsp" },
      { name: "ground coriander", quantity: 1, unit: "tsp" },
      { name: "cinnamon", quantity: 0.5, unit: "tsp" },
      { name: "hummus", quantity: 400, unit: "g" },
      { name: "pita bread", quantity: 1, unit: "pack" },
      { name: "flat-leaf parsley", quantity: 1, unit: "bunch" },
      { name: "lemon", quantity: 1, unit: "each" },
    ],
    method: [
      "Grate onion and squeeze out excess moisture. Combine with lamb mince, garlic, cumin, coriander and cinnamon. Season well.",
      "Shape mixture into 12 oval koftas around skewers or leave as patties.",
      "Heat a grill pan or BBQ over high heat. Cook koftas 3–4 minutes per side until cooked through and charred.",
      "Spread hummus across a large plate. Arrange koftas on top.",
      "Scatter parsley over, squeeze lemon juice and serve with warm pita.",
    ],
    tags: ["gluten-free-option", "family-friendly"],
    imageQuery: "lamb kofta hummus middle eastern mezze",
    estimatedCost: 24,
  },
  {
    id: "chicken-shawarma",
    name: "Chicken Shawarma Wraps",
    description: "Juicy marinated chicken with garlic sauce, pickles and fresh tomato rolled in warm flatbread.",
    cuisine: "middle-eastern",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 15,
    difficulty: "easy",
    ingredients: [
      { name: "chicken thigh fillets", quantity: 800, unit: "g" },
      { name: "greek yogurt", quantity: 150, unit: "g" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "ground cumin", quantity: 2, unit: "tsp" },
      { name: "smoked paprika", quantity: 2, unit: "tsp" },
      { name: "turmeric", quantity: 0.5, unit: "tsp" },
      { name: "flatbreads", quantity: 1, unit: "pack" },
      { name: "cherry tomatoes", quantity: 200, unit: "g" },
      { name: "lebanese cucumber", quantity: 1, unit: "each" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
    ],
    method: [
      "Mix yogurt, 3 crushed garlic cloves, cumin, paprika and turmeric. Coat chicken and marinate 10 minutes (or overnight).",
      "Heat oil in a heavy pan over high heat. Cook chicken 5–6 minutes per side until golden and cooked through. Rest 3 minutes, then slice.",
      "Make garlic sauce: mix remaining garlic into remaining yogurt with a pinch of salt.",
      "Warm flatbreads in a dry pan. Layer with sliced chicken, tomatoes and cucumber.",
      "Drizzle garlic sauce over and fold to wrap.",
    ],
    tags: ["quick", "dairy-free-option"],
    imageQuery: "chicken shawarma flatbread garlic sauce",
    estimatedCost: 20,
  },
  {
    id: "beef-tagine",
    name: "Slow-Cooked Beef Tagine",
    description: "Moroccan-spiced beef with dried apricots and chickpeas over fluffy couscous — deeply fragrant and comforting.",
    cuisine: "middle-eastern",
    primaryProtein: "beef",
    servings: 4,
    cookTimeMinutes: 90,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "beef chuck diced", quantity: 800, unit: "g" },
      { name: "brown onion", quantity: 2, unit: "each" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "ras el hanout spice", quantity: 2, unit: "tbsp" },
      { name: "crushed tomatoes", quantity: 400, unit: "g" },
      { name: "dried apricots", quantity: 100, unit: "g" },
      { name: "chickpeas drained", quantity: 400, unit: "g" },
      { name: "beef stock", quantity: 250, unit: "ml" },
      { name: "couscous", quantity: 300, unit: "g" },
      { name: "fresh coriander", quantity: 1, unit: "bunch" },
    ],
    method: [
      "Season beef. Brown in batches in a heavy casserole over high heat. Set aside.",
      "Cook onions in the same pot until soft, 5 minutes. Add garlic and ras el hanout, stir 1 minute.",
      "Return beef. Add tomatoes, apricots, chickpeas and stock. Bring to a simmer.",
      "Cover and cook on low heat 1.5 hours until beef is tender. Season to taste.",
      "Prepare couscous per packet. Serve tagine over couscous topped with coriander.",
    ],
    tags: ["freezer-friendly", "slow-cook", "gluten-free-option"],
    imageQuery: "moroccan beef tagine couscous apricot",
    estimatedCost: 28,
  },
  {
    id: "falafel-pita",
    name: "Crispy Falafel Pita",
    description: "Golden herb-packed falafel in warm pita with tahini, pickled vegetables and fresh salad.",
    cuisine: "middle-eastern",
    primaryProtein: "tofu",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 20,
    difficulty: "medium",
    ingredients: [
      { name: "chickpeas drained", quantity: 800, unit: "g" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "ground cumin", quantity: 2, unit: "tsp" },
      { name: "fresh coriander", quantity: 1, unit: "bunch" },
      { name: "flat-leaf parsley", quantity: 1, unit: "bunch" },
      { name: "pita bread", quantity: 1, unit: "pack" },
      { name: "tahini", quantity: 4, unit: "tbsp" },
      { name: "lemon", quantity: 2, unit: "each" },
      { name: "vegetable oil", quantity: 4, unit: "tbsp" },
    ],
    method: [
      "Blitz chickpeas, onion, garlic, cumin, coriander and parsley in a food processor until coarse. Season well.",
      "Shape into 16 patties. Refrigerate 10 minutes to firm up.",
      "Heat oil in a pan over medium-high heat. Fry falafel 3 minutes per side until deep golden.",
      "Mix tahini with lemon juice and 3 tbsp water to make sauce.",
      "Warm pitas. Fill with falafel, drizzle tahini and add any salad you like.",
    ],
    tags: ["vegan", "vegetarian", "dairy-free"],
    imageQuery: "crispy falafel pita tahini herbs",
    estimatedCost: 14,
  },

  // ── Japanese ──────────────────────────────────────────────────────────────
  {
    id: "teriyaki-salmon-bowl",
    name: "Teriyaki Salmon Rice Bowl",
    description: "Glazed salmon over steamed rice with edamame, avocado and a sweet teriyaki sauce.",
    cuisine: "japanese",
    primaryProtein: "seafood",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "tasmanian atlantic salmon portions", quantity: 600, unit: "g" },
      { name: "jasmine rice", quantity: 300, unit: "g" },
      { name: "soy sauce", quantity: 4, unit: "tbsp" },
      { name: "honey", quantity: 2, unit: "tbsp" },
      { name: "mirin", quantity: 2, unit: "tbsp" },
      { name: "edamame", quantity: 200, unit: "g" },
      { name: "hass avocados", quantity: 2, unit: "each" },
      { name: "sesame seeds", quantity: 2, unit: "tbsp" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
    ],
    method: [
      "Cook rice per packet instructions. Mix soy, honey and mirin for teriyaki sauce.",
      "Place salmon in a cold non-stick pan, skin side down. Turn heat to medium. Cook 4 minutes until skin is crispy.",
      "Flip salmon, brush with teriyaki sauce. Cook 2 minutes more until just cooked through.",
      "Cook edamame per packet. Slice avocado.",
      "Divide rice into bowls. Top with salmon, edamame and avocado. Drizzle remaining sauce over, scatter sesame seeds and spring onions.",
    ],
    tags: ["gluten-free", "dairy-free", "healthy"],
    imageQuery: "teriyaki salmon rice bowl edamame avocado",
    estimatedCost: 28,
  },
  {
    id: "chicken-katsu-curry",
    name: "Chicken Katsu Curry",
    description: "Crispy panko chicken with Japanese golden curry sauce over steamed rice — a Japanese comfort food classic.",
    cuisine: "japanese",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 30,
    prepTimeMinutes: 20,
    difficulty: "medium",
    ingredients: [
      { name: "chicken breast fillets", quantity: 4, unit: "each" },
      { name: "panko breadcrumbs", quantity: 150, unit: "g" },
      { name: "eggs", quantity: 2, unit: "each" },
      { name: "plain flour", quantity: 60, unit: "g" },
      { name: "Japanese curry roux", quantity: 1, unit: "pack" },
      { name: "brown onion", quantity: 2, unit: "each" },
      { name: "carrot", quantity: 2, unit: "each" },
      { name: "potato", quantity: 2, unit: "each" },
      { name: "jasmine rice", quantity: 300, unit: "g" },
      { name: "vegetable oil", quantity: 4, unit: "tbsp" },
    ],
    method: [
      "Make curry: cook diced onion, carrot and potato in a pot with 600ml water for 15 minutes until tender. Break in curry roux and stir until dissolved. Simmer 5 minutes.",
      "Cook rice per packet instructions.",
      "Flatten chicken to even thickness. Coat in flour, dip in beaten egg, then press into panko.",
      "Pan-fry in oil over medium heat, 4 minutes per side until golden and cooked through.",
      "Slice chicken. Serve over rice with curry poured alongside.",
    ],
    tags: ["family-friendly", "comfort-food"],
    imageQuery: "chicken katsu curry japanese rice panko",
    estimatedCost: 24,
  },
  {
    id: "gyudon-beef-bowl",
    name: "Gyudon Beef Rice Bowl",
    description: "Thinly sliced beef and onion simmered in a sweet soy broth over rice — Japan's favourite fast food, made at home.",
    cuisine: "japanese",
    primaryProtein: "beef",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "beef stir fry strips", quantity: 500, unit: "g" },
      { name: "brown onion", quantity: 2, unit: "each" },
      { name: "soy sauce", quantity: 4, unit: "tbsp" },
      { name: "mirin", quantity: 3, unit: "tbsp" },
      { name: "sake or dry sherry", quantity: 2, unit: "tbsp" },
      { name: "sugar", quantity: 1, unit: "tbsp" },
      { name: "dashi stock", quantity: 200, unit: "ml" },
      { name: "jasmine rice", quantity: 300, unit: "g" },
      { name: "pickled ginger", quantity: 60, unit: "g" },
    ],
    method: [
      "Cook rice per packet instructions.",
      "Slice onions into thin half-moons. Combine soy, mirin, sake, sugar and dashi in a bowl.",
      "Heat a wide pan over medium heat. Cook onions in the broth mixture for 5 minutes until softened.",
      "Add beef strips in a single layer. Cook 2–3 minutes, turning once, until just cooked.",
      "Ladle beef and broth over rice bowls. Top with pickled ginger.",
    ],
    tags: ["quick", "dairy-free"],
    imageQuery: "gyudon beef rice bowl japanese soy",
    estimatedCost: 20,
  },
  {
    id: "miso-ramen",
    name: "Miso Pork Ramen",
    description: "Richly flavoured miso broth with tender pork, ramen noodles, soft-boiled egg and crispy corn.",
    cuisine: "japanese",
    primaryProtein: "pork",
    servings: 4,
    cookTimeMinutes: 30,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "pork belly slices", quantity: 500, unit: "g" },
      { name: "ramen noodles", quantity: 400, unit: "g" },
      { name: "white miso paste", quantity: 4, unit: "tbsp" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "sesame oil", quantity: 1, unit: "tbsp" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "fresh ginger", quantity: 20, unit: "g" },
      { name: "chicken stock", quantity: 1200, unit: "ml" },
      { name: "eggs", quantity: 4, unit: "each" },
      { name: "spring onions", quantity: 1, unit: "bunch" },
    ],
    method: [
      "Boil eggs for 7 minutes for soft yolk. Cool in iced water, peel and halve.",
      "Fry pork belly in a dry pan over high heat until crispy and cooked through. Slice.",
      "Sauté garlic and ginger in sesame oil 1 minute. Add chicken stock and bring to a simmer.",
      "Whisk miso and soy into the broth. Do not boil after adding miso.",
      "Cook noodles per packet. Divide into bowls with broth, pork, egg halves and spring onions.",
    ],
    tags: ["comfort-food", "dairy-free"],
    imageQuery: "miso ramen pork egg noodles japanese",
    estimatedCost: 22,
  },

  // ── Mediterranean ─────────────────────────────────────────────────────────
  {
    id: "chicken-pesto-pasta",
    name: "Chicken Pesto Pasta",
    description: "Grilled chicken with al dente pasta tossed in fresh basil pesto and cherry tomatoes.",
    cuisine: "mediterranean",
    primaryProtein: "chicken",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "chicken breast fillets", quantity: 600, unit: "g" },
      { name: "penne pasta", quantity: 400, unit: "g" },
      { name: "basil pesto", quantity: 190, unit: "g" },
      { name: "cherry tomatoes", quantity: 250, unit: "g" },
      { name: "parmesan grated", quantity: 60, unit: "g" },
      { name: "olive oil extra virgin", quantity: 2, unit: "tbsp" },
      { name: "lemon", quantity: 1, unit: "each" },
      { name: "baby spinach", quantity: 60, unit: "g" },
    ],
    method: [
      "Cook pasta in salted boiling water until al dente. Reserve ½ cup pasta water.",
      "Season chicken. Pan-fry in oil over medium-high heat, 4–5 minutes per side until cooked through. Rest then slice.",
      "Halve cherry tomatoes. Toss warm drained pasta with pesto, adding pasta water to loosen.",
      "Fold through spinach, tomatoes and lemon juice. Season to taste.",
      "Divide into bowls, top with sliced chicken and parmesan.",
    ],
    tags: ["quick", "family-friendly"],
    imageQuery: "chicken pesto pasta cherry tomatoes parmesan",
    estimatedCost: 20,
  },
  {
    id: "seafood-paella",
    name: "Prawn & Chorizo Paella",
    description: "Saffron-scented Spanish rice with king prawns, chorizo and mussels cooked in a wide pan.",
    cuisine: "mediterranean",
    primaryProtein: "seafood",
    servings: 4,
    cookTimeMinutes: 35,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "raw king prawns", quantity: 500, unit: "g" },
      { name: "chorizo", quantity: 200, unit: "g" },
      { name: "arborio rice", quantity: 300, unit: "g" },
      { name: "chicken stock", quantity: 800, unit: "ml" },
      { name: "brown onion", quantity: 1, unit: "each" },
      { name: "red capsicum", quantity: 2, unit: "each" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "crushed tomatoes", quantity: 200, unit: "g" },
      { name: "saffron threads", quantity: 0.5, unit: "tsp" },
      { name: "lemon", quantity: 2, unit: "each" },
    ],
    method: [
      "Steep saffron in 50ml warm stock. Slice chorizo, dice onion and capsicum.",
      "Fry chorizo in a wide pan over medium heat until crispy. Remove. Cook onion and capsicum in the fat for 5 minutes.",
      "Add garlic and rice, stir 1 minute. Add tomatoes, saffron stock and remaining stock. Season.",
      "Simmer uncovered on medium-low heat 15 minutes — do not stir — until rice is almost tender.",
      "Nestle prawns and chorizo into the rice. Cook 5 minutes until prawns are pink and rice is cooked. Serve with lemon wedges.",
    ],
    tags: ["gluten-free", "dinner-party"],
    imageQuery: "seafood paella prawns chorizo saffron",
    estimatedCost: 32,
  },
  {
    id: "baked-mediterranean-fish",
    name: "Mediterranean Baked Fish",
    description: "White fish baked on a bed of olives, capers, tomatoes and herbs — simple, bright and healthy.",
    cuisine: "mediterranean",
    primaryProtein: "seafood",
    servings: 4,
    cookTimeMinutes: 20,
    prepTimeMinutes: 10,
    difficulty: "easy",
    ingredients: [
      { name: "barramundi fillets", quantity: 700, unit: "g" },
      { name: "cherry tomatoes", quantity: 300, unit: "g" },
      { name: "kalamata olives", quantity: 120, unit: "g" },
      { name: "capers", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 3, unit: "clove" },
      { name: "olive oil extra virgin", quantity: 3, unit: "tbsp" },
      { name: "lemon", quantity: 2, unit: "each" },
      { name: "fresh thyme", quantity: 1, unit: "pack" },
      { name: "crusty bread", quantity: 1, unit: "loaf" },
    ],
    method: [
      "Preheat oven to 200°C. Halve cherry tomatoes and toss with olives, capers, garlic, thyme and 2 tbsp olive oil in a baking dish.",
      "Roast vegetables 10 minutes until tomatoes begin to burst.",
      "Season fish. Lay on top of vegetables, drizzle with remaining oil and lemon juice.",
      "Bake 12–15 minutes until fish flakes easily.",
      "Serve straight from the dish with crusty bread.",
    ],
    tags: ["gluten-free-option", "healthy", "one-pan"],
    imageQuery: "baked barramundi mediterranean tomatoes olives",
    estimatedCost: 26,
  },
  {
    id: "lamb-mediterranean",
    name: "Herb-Crusted Lamb Rack",
    description: "French-trimmed lamb rack with a herbed breadcrumb crust, roasted vegetables and rosemary jus.",
    cuisine: "mediterranean",
    primaryProtein: "lamb",
    servings: 4,
    cookTimeMinutes: 25,
    prepTimeMinutes: 15,
    difficulty: "medium",
    ingredients: [
      { name: "lamb racks french trimmed", quantity: 2, unit: "each" },
      { name: "fresh rosemary", quantity: 2, unit: "sprig" },
      { name: "garlic", quantity: 4, unit: "clove" },
      { name: "breadcrumbs", quantity: 80, unit: "g" },
      { name: "parmesan grated", quantity: 40, unit: "g" },
      { name: "dijon mustard", quantity: 2, unit: "tbsp" },
      { name: "zucchini", quantity: 3, unit: "each" },
      { name: "cherry tomatoes", quantity: 250, unit: "g" },
      { name: "olive oil extra virgin", quantity: 3, unit: "tbsp" },
    ],
    method: [
      "Preheat oven to 200°C. Mix breadcrumbs, parmesan, chopped rosemary and garlic.",
      "Sear lamb racks in an ovenproof pan over high heat, 1 minute each side.",
      "Brush fat side with mustard, press breadcrumb mixture on top.",
      "Roast 18 minutes for medium-rare. Rest 5 minutes before carving.",
      "Toss zucchini and tomatoes in oil, roast alongside lamb. Serve together.",
    ],
    tags: ["dinner-party", "gluten-free-option"],
    imageQuery: "herb crusted lamb rack rosemary vegetables",
    estimatedCost: 38,
  },
];

const MOCK_SNACKS: SnackItem[] = [
  { id: "snack-1", name: "Mixed Nuts", description: "A daily handful — heart-healthy and filling", quantity: 1, unit: "bag (500g)", estimatedCost: 9.00 },
  { id: "snack-2", name: "Fresh Fruit", description: "Bananas, apples and whatever's in season", quantity: 2, unit: "kg mixed", estimatedCost: 8.00 },
  { id: "snack-3", name: "Hummus & Rice Crackers", description: "A satisfying afternoon snack", quantity: 1, unit: "pack each", estimatedCost: 6.00 },
  { id: "snack-4", name: "Dark Chocolate 70%", description: "A square or two after dinner", quantity: 2, unit: "bars (100g)", estimatedCost: 7.00 },
  { id: "snack-5", name: "Greek Yogurt", description: "Breakfast or snack with a drizzle of honey", quantity: 2, unit: "tubs (500g)", estimatedCost: 11.00 },
];

export function generateMockMealPlan(preferences: UserPreferences): WeeklyMealPlan {
  const planId = `mock-plan-${Date.now()}`;
  const library = getRecipeLibrary();

  // Filter recipes by dietary requirements, cuisine, and protein preferences
  let pool = [...library];

  // Cuisine filter first (broadest)
  if (preferences.cuisinePreferences.length > 0) {
    const filtered = pool.filter((r) => preferences.cuisinePreferences.includes(r.cuisine as CuisinePreference));
    if (filtered.length >= 4) pool = filtered;
  }

  if (preferences.proteinPreferences.length > 0 && !preferences.proteinPreferences.includes("no-preference")) {
    const filtered = pool.filter(
      (r) => r.primaryProtein && preferences.proteinPreferences.includes(r.primaryProtein as never)
    );
    if (filtered.length >= 4) pool = filtered;
  }

  if (preferences.dietaryRequirements.includes("vegan") || preferences.dietaryRequirements.includes("vegetarian")) {
    pool = pool.filter((r) => r.tags.includes("vegan") || r.tags.includes("vegetarian") || r.primaryProtein === "tofu");
    if (pool.length === 0) pool = library;
  }

  // Shuffle pool for variety then pick 7 distinct dinners
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const dinners: PlannedMeal[] = Array.from({ length: 7 }, (_, i) => {
    const recipe = shuffled[i % shuffled.length];
    return {
      id: `meal-${planId}-${i}`,
      dayIndex: i,
      mealType: "dinner" as const,
      recipe: { ...recipe, servings: preferences.defaultServings },
      servings: preferences.defaultServings,
    };
  });

  // Pick 5 lunches if requested (simpler versions)
  const lunches: PlannedMeal[] = preferences.includeLunches
    ? Array.from({ length: 5 }, (_, i) => {
        const recipe = shuffled[(i + 3) % shuffled.length];
        return {
          id: `lunch-${planId}-${i}`,
          dayIndex: i,
          mealType: "lunch" as const,
          recipe: { ...recipe, id: `${recipe.id}-lunch`, name: `${recipe.name} (Lunch)`, servings: preferences.defaultServings },
          servings: preferences.defaultServings,
        };
      })
    : [];

  return {
    id: planId,
    generatedAt: Date.now(),
    meals: [...dinners, ...lunches],
    snacks: preferences.includeSnacks ? MOCK_SNACKS : [],
    preferenceSnapshot: preferences,
  };
}
